# Site settings
title: Folkesson SuperTech AB
description: Systemutveckling, konsulttjänster och utbildning inom mjukvaruutveckling.
baseurl: "/"
url: "https://folkessontech.com"
lang: sv-SE
timezone: Europe/Stockholm
author:
  name: "Andreas Folkesson"
  email: "folkesson@gmail.com"
  linkedin: "https://www.linkedin.com/in/andreas-folkesson-71a0538/"
logo: /assets/images/headshot_circle.webp
search: false # true, false (default)
feed: false

# Theme settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

# Build settings
markdown: kramdown
plugins:
  #- jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache

# Compile settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - .gitignore
  - .jekyll-cache

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  services:
    output: true
    permalink: /:collection/:path/
  en_services:
    output: true
    permalink: /:collection/:path/

# Pagination settings
paginate: 5
paginate_path: /page:num/

# Front matter defaults
defaults:
  - scope:
      path: "*.md"
      type: pages
    values:
      layout: page
  # _services
  - scope:
      path: "_services"
      type: services
    values:
      layout: page
      read_time: false
  # _en_services
  - scope:
      path: "_en_services"
      type: en_services
    values:
      layout: page
      read_time: false

  - scope:
      path: "assets/**/*"
      type: "assets"
    values:
      layout: null