title: Andreas Folkesson
description: Random stuff from me
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
