# Site settings
title: Andreas Folkesson
description: Random stuff from me
baseurl: ""
url: "https://supersalad.github.io"
lang: en-US
timezone: Europe/Stockholm

# Theme settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@main"
skin: default

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links

# Navigation
include:
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Pagination settings
paginate: 5
paginate_path: /page:num/

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page