# Site settings
title: Folkesson SuperTech AB
description: Random stuff from me
baseurl: "/"
url: "https://supersalad.github.io"
lang: en-US
timezone: Europe/Stockholm
author:
  name: "Andreas Folkesson"
  email: "folkesson@gmail.com"
  linkedin: "https://www.linkedin.com/in/andreas-folkesson-71a0538/"
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: false # true, false (default)
feed: false

# Theme settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

# Build settings
markdown: kramdown
plugins:
  #- jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache

# Compile settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - .gitignore
  - .jekyll-cache

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Pagination settings
paginate: 5
paginate_path: /page:num/

# Front matter defaults
defaults:
  - scope:
      path: "*.md"
      type: pages
    values:
      layout: page
  - scope:
      path: "assets/**/*"
      type: "assets"
    values:
      layout: null