name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [dispatch-event]

  workflow_dispatch:
    inputs:
      tagname:
        description: 'Release tag to deploy'
        required: true
        type: string
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
      
      - name: Set tag variable
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tagname }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=${{ github.event.client_payload.tagname }}" >> $GITHUB_ENV
          fi

      - name: Download Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY_CLASSIC }}
        run: |
          gh release download --repo https://github.com/supersalad/consultancy_webpage "${{ env.RELEASE_TAG }}" --pattern "build.zip"
          unzip build.zip -d build

      - name: Copy and commit changes
        run: |
          rm -r static
          cp -r build/* .
          rm -r build
          rm build.zip
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy release ${{ env.RELEASE_TAG }}"
          git push